# Generated by Django 5.2.1 on 2025-06-21 21:11

import django.core.validators
import django.db.models.deletion
import timeoffreq.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leavetype", "0002_departmentbasedleavetype_created_at_and_more"),
        ("payperiod", "0002_payperiod_created_at_payperiod_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeoffRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date_time",
                    models.DateTimeField(
                        help_text="Start date and time of the requested leave",
                        verbose_name="Start Date and Time",
                    ),
                ),
                (
                    "end_date_time",
                    models.DateTimeField(
                        help_text="End date and time of the requested leave",
                        verbose_name="End Date and Time",
                    ),
                ),
                (
                    "time_off_duration",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Duration in hours, automatically calculated based on start and end date/time",
                        max_digits=5,
                        verbose_name="Time Off Duration",
                    ),
                ),
                (
                    "employee_leave_reason",
                    models.CharField(
                        help_text="Reason for the leave request",
                        max_length=255,
                        verbose_name="Leave Reason",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Time off Status",
                    ),
                ),
                (
                    "medical_document_proof",
                    models.FileField(
                        blank=True,
                        help_text="Upload a medical document proof for applicable leave requests (only PDF, JPG, JPEG, PNG allowed)",
                        null=True,
                        upload_to=timeoffreq.utils.pto_document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Medical Document Proof",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the time off request was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the time off request was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the time off request was approved",
                        null=True,
                        verbose_name="Approved At",
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the time off request was rejected",
                        null=True,
                        verbose_name="Rejected At",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved the time off request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_timeoff_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeoff_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employee",
                    ),
                ),
                (
                    "reference_pay_period",
                    models.ForeignKey(
                        help_text="Pay period during which the time off is requested",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeoff_requests",
                        to="payperiod.payperiod",
                        verbose_name="Pay Period",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who rejected the time off request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_timeoff_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Rejected By",
                    ),
                ),
                (
                    "requested_leave_type",
                    models.ForeignKey(
                        help_text="Type of leave requested by the employee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeoff_requests",
                        to="leavetype.departmentbasedleavetype",
                        verbose_name="Leave Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Off Request",
                "verbose_name_plural": "Time Off Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "status"],
                        name="timeoffreq__employe_301089_idx",
                    ),
                    models.Index(
                        fields=["start_date_time", "end_date_time"],
                        name="timeoffreq__start_d_a25fd4_idx",
                    ),
                ],
            },
        ),
    ]
