# Generated by Django 5.2.1 on 2025-06-23 13:18

import django.core.validators
import django.db.models.deletion
import timeoffreq.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeoffreq", "0003_alter_timeoffrequest_reference_pay_period"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeoffrequest",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="timeoffrequest",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="timeoffrequest",
            name="medical_document_proof",
        ),
        migrations.RemoveField(
            model_name="timeoffrequest",
            name="rejected_at",
        ),
        migrations.RemoveField(
            model_name="timeoffrequest",
            name="rejected_by",
        ),
        migrations.AddField(
            model_name="timeoffrequest",
            name="document_proof",
            field=models.FileField(
                blank=True,
                help_text="Upload a document proof for applicable leave requests (only PDF, JPG, JPEG, PNG allowed)",
                null=True,
                upload_to=timeoffreq.utils.pto_document_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="Document Proof",
            ),
        ),
        migrations.AddField(
            model_name="timeoffrequest",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the time off request was last reviewed (approved or rejected)",
                null=True,
                verbose_name="Reviewed At",
            ),
        ),
        migrations.AddField(
            model_name="timeoffrequest",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last reviewed (approved or rejected) the time off request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_timeoff_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed By",
            ),
        ),
        migrations.AlterField(
            model_name="timeoffrequest",
            name="time_off_duration",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Duration in hours, automatically calculated based on start and end date/time",
                max_digits=5,
                verbose_name="Time Off Duration",
            ),
        ),
    ]
