# Generated by Django 5.2.1 on 2025-08-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timeoffreq", "0004_remove_timeoffrequest_approved_at_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="timeoffrequest",
            new_name="time_off_re_employe_41a49c_idx",
            old_name="timeoffreq__employe_301089_idx",
        ),
        migrations.RenameIndex(
            model_name="timeoffrequest",
            new_name="time_off_re_start_d_8102b3_idx",
            old_name="timeoffreq__start_d_a25fd4_idx",
        ),
        migrations.AlterModelTable(
            name="timeoffrequest",
            table="time_off_requests",
        ),
    ]
