# Generated by Django 5.2.1 on 2025-05-13 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accuralrates', '0001_initial'),
        ('employeetype', '0001_initial'),
        ('payfrequency', '0003_remove_pay_frequency_user'),
        ('yearofexperience', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PTOBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pto_balance', models.FloatField(default=0.0)),
                ('accrual_rate', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pto_balances', to='accuralrates.accrualrates')),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_balances', to='employeetype.employeetype')),
                ('pay_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_balances', to='payfrequency.pay_frequency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pto_balance', to=settings.AUTH_USER_MODEL)),
                ('year_of_experience', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pto_balances', to='yearofexperience.yearofexperience')),
            ],
            options={
                'verbose_name': 'PTO Balance',
                'verbose_name_plural': 'PTO Balance',
            },
        ),
    ]
