# Generated by Django 5.2.1 on 2025-09-30 18:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accuralrates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PTOBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pto_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MaxValueValidator(340)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accrual_rate', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pto_balances', to='accuralrates.accrualrates')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pto_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PTO Balance',
                'verbose_name_plural': 'PTO Balance',
                'db_table': 'pto_balances',
                'constraints': [models.CheckConstraint(condition=models.Q(('pto_balance__lte', 340)), name='PTO_balance_max_340')],
            },
        ),
    ]
