# Generated by Django 5.2.1 on 2025-08-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ptobalance", "0004_ptobalance_created_at_ptobalance_updated_at"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ptobalance",
            table="pto_balances",
        ),
    ]
