# Generated by Django 5.2.1 on 2025-09-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptobalance', '0005_alter_ptobalance_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptobalance',
            name='employee_type',
        ),
        migrations.RemoveField(
            model_name='ptobalance',
            name='pay_frequency',
        ),
        migrations.RemoveField(
            model_name='ptobalance',
            name='year_of_experience',
        ),
    ]
