# Generated by Django 5.2.1 on 2025-05-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biweeklycron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Biweekly Cron',
                'verbose_name_plural': 'Biweekly Crons',
            },
        ),
    ]
