# Generated by Django 5.2.1 on 2025-06-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clock',
            options={'ordering': ['-clock_in_time'], 'verbose_name': 'Clock Entry'},
        ),
    ]
