# Generated by Django 5.2.1 on 2025-06-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("timeclock", "0003_clock_is_holiday")]

    operations = [migrations.AlterModelOptions(name="clock", options={"ordering": ["-clock_in_time"], "verbose_name": "Clock Entry", "verbose_name_plural": "Clock Entries"})]
