# Generated by Django 5.2.1 on 2025-08-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timeclock", "0005_clock_created_at_clock_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clock",
            options={
                "ordering": ["-clock_in_time"],
                "verbose_name": "Punch Entry",
                "verbose_name_plural": "Punch Entries",
            },
        ),
        migrations.AlterModelTable(
            name="clock",
            table="punch_entries",
        ),
    ]
