# Generated by Django 5.2.1 on 2025-08-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leavetype", "0002_departmentbasedleavetype_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departmentbasedleavetype",
            options={
                "verbose_name": "Unit Leave Type",
                "verbose_name_plural": "Unit Leave Types",
            },
        ),
        migrations.AlterModelOptions(
            name="leavetype",
            options={
                "verbose_name": "Leave Type",
                "verbose_name_plural": "Leave Types",
            },
        ),
        migrations.AlterModelTable(
            name="departmentbasedleavetype",
            table="unit_based_leave_types",
        ),
        migrations.AlterModelTable(
            name="leavetype",
            table="leave_types",
        ),
    ]
