# Generated by Django 5.2.1 on 2025-09-30 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaxSickValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_unverified_sick_leave', models.DecimalField(decimal_places=2, default=64.0, help_text="Base unverified sick leave 64 hrs. Automatically Prorated by FTE. Don't Modify unless the policy changes maximum value.", max_digits=5)),
                ('upfront_verified', models.DecimalField(decimal_places=2, default=96.0, help_text="Base upfront verified sick leave 96 hrs. Automatically Prorated by FTE. Don't Modify unless the policy changes upfront verified sick leave value.", max_digits=5)),
                ('accrued_rate', models.DecimalField(decimal_places=10, default=2.4615384615, help_text='Fixed monthly accrual rate. Not prorated by FTE.', max_digits=11)),
                ('threshold_FVSL', models.DecimalField(decimal_places=2, default=96.0, help_text='Max 96 hrs/year for verified family care. Not prorated. Resets yearly.', max_digits=5)),
            ],
            options={
                'verbose_name': 'Sick Leave Constants value (Global)',
                'verbose_name_plural': 'Sick Leave Constants (Global)',
                'db_table': 'sick_leave_constants',
            },
        ),
        migrations.CreateModel(
            name='SickLeaveProratedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Policy name (e.g., 'Full-Time', 'Part-Time', '70% Policy').", max_length=100, unique=True)),
                ('fte_value', models.DecimalField(decimal_places=2, help_text='FTE value: 1.0 for Full-Time, >0.5 for Part-Time (per SEMO policy).', max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1.0)])),
                ('prorated_unverified_sick_leave', models.DecimalField(blank=True, decimal_places=2, help_text="Base unverified sick leave 64 hrs. Automatically Prorated by FTE. Don't Modify unless the policy changes maximum value.", max_digits=5, null=True)),
                ('prorated_upfront_verified', models.DecimalField(blank=True, decimal_places=2, help_text="Base upfront verified sick leave 96 hrs. Automatically Prorated by FTE. Don't Modify unless the policy changes upfront verified sick leave value.", max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Sick Leave Prorated Value',
                'verbose_name_plural': 'Sick Leave Prorated Values',
                'db_table': 'sick_leave_prorated_values',
                'unique_together': {('name', 'fte_value')},
            },
        ),
    ]
