# Generated by Django 5.2.1 on 2025-06-20 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sickpolicy",
            "0003_alter_sickleaveproratedvalue_prorated_unverified_sick_leave_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sickleaveproratedvalue",
            name="fte_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="FTE value: 1.0 for Full-Time, >0.5 for Part-Time (per SEMO policy).",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sickleaveproratedvalue",
            name="prorated_unverified_sick_leave",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Base unverified sick leave 64 hrs. Automatically Prorated by FTE. Don't Modify unless the policy changes maximum value.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sickleaveproratedvalue",
            name="prorated_upfront_verified",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Base upfront verified sick leave 96 hrs. Automatically Prorated by FTE. Don't Modify unless the policy changes upfront verified sick leave value.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
