# Generated by Django 5.2.1 on 2025-06-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("sickpolicy", "0005_alter_sickleaveproratedvalue_options_and_more")]

    operations = [migrations.RenameField(model_name="maxsickvalue", old_name="allow_verified_family_care_limit", new_name="threshold_FVSL")]
