# Generated by Django 5.2.1 on 2025-06-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sickpolicy",
            "0006_rename_allow_verified_family_care_limit_maxsickvalue_threshold_fvsl",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="maxsickvalue",
            old_name="threshold_FVSL",
            new_name="allow_verified_family_care_limit",
        ),
    ]
