# Generated by Django 5.2.1 on 2025-08-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sickpolicy",
            "0008_rename_allow_verified_family_care_limit_maxsickvalue_threshold_fvsl",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="maxsickvalue",
            table="max_sick_value",
        ),
        migrations.AlterModelTable(
            name="sickleaveproratedvalue",
            table="sick_leave_prorated_values",
        ),
    ]
