# Generated by Django 5.2.1 on 2025-09-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sickpolicy", "0009_alter_maxsickvalue_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maxsickvalue",
            options={
                "verbose_name": "Sick Leave Constants value (Global)",
                "verbose_name_plural": "Sick Leave Constants (Global)",
            },
        ),
        migrations.AlterModelTable(
            name="maxsickvalue",
            table="sick_leave_constants",
        ),
    ]
