# Generated by Django 5.2.1 on 2025-05-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [migrations.CreateModel(name="PayFrequency", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("frequency", models.CharField(max_length=100, unique=True))], options={"verbose_name": "Pay Frequency", "verbose_name_plural": "Pay Frequencies"})]
