# Generated by Django 5.2.1 on 2025-05-08 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payfrequency", "0001_initial"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [migrations.CreateModel(name="pay_frequency", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("frequency", models.CharField(max_length=100, unique=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pay_frequency", to=settings.AUTH_USER_MODEL))], options={"verbose_name": "Pay Frequency", "verbose_name_plural": "Pay Frequencies"}), migrations.DeleteModel(name="PayFrequency")]
