# Generated by Django 5.2.1 on 2025-05-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payfrequency', '0002_pay_frequency_delete_payfrequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay_frequency',
            name='user',
        ),
    ]
