# Generated by Django 5.2.1 on 2025-08-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payfrequency", "0004_pay_frequency_created_at_pay_frequency_updated_at"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="pay_frequency",
            table="pay_frequencies",
        ),
    ]
