# Generated by Django 5.2.1 on 2025-09-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payfrequency", "0005_alter_pay_frequency_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="pay_frequency",
            table="payfrequencies",
        ),
    ]
