# Generated by Django 5.2.1 on 2025-09-30 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Shift Type',
                'verbose_name_plural': 'Shift Types',
                'db_table': 'shift_types',
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, unique=True)),
            ],
            options={
                'verbose_name': 'Squad',
                'verbose_name_plural': 'Squads',
                'db_table': 'squads',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftmanagement.squad')),
            ],
            options={
                'verbose_name': 'Squad Employee',
                'verbose_name_plural': 'Squad Employees',
                'db_table': 'employees_in_squads',
            },
        ),
        migrations.CreateModel(
            name='SquadShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftmanagement.shifttype')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftmanagement.squad')),
            ],
            options={
                'db_table': 'shift_assingments_to_squads',
                'ordering': ['shift_start', 'squad__name'],
                'unique_together': {('squad', 'shift_start')},
            },
        ),
    ]
