# Generated by Django 5.2.1 on 2025-07-03 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shiftmanagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SquadShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift_start", models.DateTimeField()),
                ("shift_end", models.DateTimeField()),
                (
                    "shift_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shiftmanagement.shifttype",
                    ),
                ),
                (
                    "squad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shiftmanagement.squad",
                    ),
                ),
            ],
            options={
                "ordering": ["shift_start", "squad__name"],
                "unique_together": {("squad", "shift_start")},
            },
        ),
        migrations.DeleteModel(
            name="ShiftAssignment",
        ),
    ]
