# Generated by Django 5.2.1 on 2025-08-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shiftmanagement", "0002_squadshift_delete_shiftassignment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "verbose_name": "Squad Employee",
                "verbose_name_plural": "Squad Employees",
            },
        ),
        migrations.AlterModelOptions(
            name="shifttype",
            options={
                "verbose_name": "Shift Type",
                "verbose_name_plural": "Shift Types",
            },
        ),
        migrations.AlterModelOptions(
            name="squad",
            options={"verbose_name": "Squad", "verbose_name_plural": "Squads"},
        ),
        migrations.AlterModelTable(
            name="employee",
            table="employees_in_squads",
        ),
        migrations.AlterModelTable(
            name="shifttype",
            table="shift_types",
        ),
        migrations.AlterModelTable(
            name="squad",
            table="squads",
        ),
    ]
