# Generated by Django 5.2.1 on 2025-08-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "shiftmanagement",
            "0003_alter_employee_options_alter_shifttype_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="squadshift",
            table="shift_assingments_to_squads",
        ),
    ]
