# Generated by Django 5.2.1 on 2025-06-09 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_userprofile'),
        ('leavetype', '0001_initial'),
        ('payperiod', '0001_initial'),
        ('ptorequest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PTORequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(help_text='The exact date and time the PTO request begins (in UTC).', verbose_name='Start Date and Time')),
                ('end_date_time', models.DateTimeField(help_text='The exact date and time the PTO request ends (in UTC).', verbose_name='End Date and Time')),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Automatically calculated total hours requested for this specific PTO entry.', max_digits=5, null=True, verbose_name='Total Hours')),
                ('reason', models.TextField(verbose_name='Reason for Request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Request Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_requests', to='department.department', verbose_name='Department')),
                ('leave_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pto_requests', to='leavetype.leavetype', verbose_name='Leave Type')),
                ('pay_period', models.ForeignKey(blank=True, help_text='The pay period to which this PTO request portion belongs. Assigned automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pto_requests', to='payperiod.payperiod', verbose_name='Associated Pay Period')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_requests', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'PTO Request',
                'verbose_name_plural': 'PTO Requests',
                'ordering': ['-start_date_time'],
            },
        ),
        migrations.DeleteModel(
            name='PTORequest',
        ),
    ]
