# Generated by Django 5.2.1 on 2025-06-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ptorequest", "0002_ptorequests_delete_ptorequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ptorequests",
            options={
                "ordering": ["-start_date_time"],
                "verbose_name": "Time off Request",
                "verbose_name_plural": "Time off Requests",
            },
        ),
    ]
