# Generated by Django 5.2.1 on 2025-06-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ptorequest", "0003_alter_ptorequests_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ptorequests",
            name="total_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Automatically calculated total hours requested for this specific PTO entry.",
                max_digits=4,
                null=True,
                verbose_name="Total Hours",
            ),
        ),
    ]
