# Generated by Django 5.2.1 on 2025-05-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptorequest', '0003_alter_ptorequests_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptorequests',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
