# Generated by Django 5.2.1 on 2025-06-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ptorequest", "0004_alter_ptorequests_total_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptorequests",
            name="medical_document",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
