# Generated by Django 5.2.1 on 2025-06-21 21:09

import ptorequest.utils.file_upload_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ptorequest", "0005_ptorequests_medical_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ptorequests",
            name="medical_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=ptorequest.utils.file_upload_helpers.pto_document_upload_path,
            ),
        ),
    ]
