# Generated by Django 5.2.1 on 2025-05-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptorequest', '0006_alter_ptorequests_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptorequests',
            name='notes',
        ),
    ]
