# Generated by Django 5.2.1 on 2025-06-03 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_userprofile'),
        ('payperiod', '0001_initial'),
        ('paytype', '0008_alter_departmentbasedpaytype_options_and_more'),
        ('ptorequest', '0007_remove_ptorequests_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ptorequests',
            options={'ordering': ['-start_date_time'], 'verbose_name': 'PTO Request', 'verbose_name_plural': 'PTO Requests'},
        ),
        migrations.AddField(
            model_name='ptorequests',
            name='pay_period',
            field=models.ForeignKey(blank=True, help_text='The pay period to which this PTO request portion belongs. Assigned automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pto_requests', to='payperiod.payperiod', verbose_name='Associated Pay Period'),
        ),
        migrations.AlterField(
            model_name='ptorequests',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_requests', to='department.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='ptorequests',
            name='end_date_time',
            field=models.DateTimeField(help_text='The exact date and time the PTO request ends (in UTC).', verbose_name='End Date and Time'),
        ),
        migrations.AlterField(
            model_name='ptorequests',
            name='pay_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_requests', to='paytype.paytype', verbose_name='Pay Type'),
        ),
        migrations.AlterField(
            model_name='ptorequests',
            name='reason',
            field=models.TextField(verbose_name='Reason for Request'),
        ),
        migrations.AlterField(
            model_name='ptorequests',
            name='start_date_time',
            field=models.DateTimeField(help_text='The exact date and time the PTO request begins (in UTC).', verbose_name='Start Date and Time'),
        ),
        migrations.AlterField(
            model_name='ptorequests',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Request Status'),
        ),
        migrations.AlterField(
            model_name='ptorequests',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Automatically calculated total hours requested for this specific PTO entry.', max_digits=5, null=True, verbose_name='Total Hours'),
        ),
        migrations.AlterField(
            model_name='ptorequests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_requests', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
    ]
