# Generated by Django 5.2.1 on 2025-06-09 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavetype', '0001_initial'),
        ('ptorequest', '0008_alter_ptorequests_options_ptorequests_pay_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptorequests',
            name='pay_types',
        ),
        migrations.AddField(
            model_name='ptorequests',
            name='leave_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pto_requests', to='leavetype.leavetype', verbose_name='Leave Type'),
        ),
    ]
