# Generated by Django 5.2.1 on 2025-09-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowIpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('description', models.CharField(blank=True, help_text="e.g., 'Main Office IP'", max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Whitelisted IP Address',
                'verbose_name_plural': 'Whitelisted IP Address',
                'db_table': 'whitelisted_ip_addresses',
            },
        ),
    ]
