# Generated by Django 5.2.1 on 2025-06-17 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        help_text="A short verb describing the action (e.g., 'liked', 'commented on').",
                        max_length=255,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The primary key of the related object.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A more detailed description of the notification.",
                        null=True,
                    ),
                ),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="URL path for the frontend to navigate to when clicking the notification.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the notification was created.",
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        default=False,
                        help_text="True if the notification has been read by the recipient.",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        help_text="The severity level of the notification.",
                        max_length=20,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user or system that initiated the notification.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="The content type of the related object (e.g., 'Post', 'Comment').",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The user who is the intended recipient of the notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read", "-timestamp"],
                        name="notificatio_recipie_028028_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="notificatio_content_e6e285_idx",
                    ),
                ],
            },
        ),
    ]
