# Generated by Django 5.2.1 on 2025-08-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notificationapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_0b4976_idx",
            old_name="notificatio_recipie_028028_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_content_3c688e_idx",
            old_name="notificatio_content_e6e285_idx",
        ),
        migrations.AlterModelTable(
            name="notification",
            table="notifications",
        ),
    ]
