# Generated by Django 5.2.1 on 2025-05-23 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytype', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBasedPayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_paytype', to='paytype.paytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_paytype', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
