# Generated by Django 5.2.1 on 2025-05-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytype', '0002_userbasedpaytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasedpaytype',
            name='pay_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_paytype', to='paytype.paytype', unique=True),
        ),
    ]
