# Generated by Django 5.2.1 on 2025-05-23 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytype', '0003_alter_userbasedpaytype_pay_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasedpaytype',
            name='pay_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paytype.paytype', unique=True),
        ),
        migrations.AlterField(
            model_name='userbasedpaytype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
