# Generated by Django 5.2.1 on 2025-05-27 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_userprofile'),
        ('paytype', '0004_alter_userbasedpaytype_pay_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentBasedPayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('pay_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paytype.paytype', unique=True)),
            ],
            options={
                'verbose_name': 'Department Based Pay Type',
                'verbose_name_plural': 'Department Based Pay Types',
            },
        ),
    ]
