# Generated by Django 5.2.1 on 2025-05-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytype', '0005_departmentbasedpaytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentbasedpaytype',
            name='pay_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paytype.paytype'),
        ),
    ]
