# Generated by Django 5.2.1 on 2025-05-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_userprofile'),
        ('paytype', '0006_alter_departmentbasedpaytype_pay_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentbasedpaytype',
            unique_together={('department', 'pay_type')},
        ),
    ]
