# Generated by Django 5.2.1 on 2025-05-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytype', '0007_alter_departmentbasedpaytype_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentbasedpaytype',
            options={'verbose_name': 'Department Leave Type', 'verbose_name_plural': 'Department  Leave Types'},
        ),
        migrations.DeleteModel(
            name='UserBasedPayType',
        ),
    ]
