# Generated by Django 5.2.1 on 2025-05-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("yearofexperience", "0001_initial")]

    operations = [migrations.AlterModelOptions(name="yearofexperience", options={})]
