# Generated by Django 5.2.1 on 2025-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("yearofexperience", "0002_alter_yearofexperience_options")]

    operations = [migrations.AlterField(model_name="yearofexperience", name="years_of_experience", field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4))]
