# Generated by Django 5.2.1 on 2025-08-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yearofexperience", "0004_yearofexperience_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="yearofexperience",
            options={
                "verbose_name": "Years of Experience",
                "verbose_name_plural": "Years of Experience",
            },
        ),
        migrations.AlterModelTable(
            name="yearofexperience",
            table="experience_years",
        ),
    ]
