# Generated by Django 5.2.1 on 2025-09-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearofexperience', '0005_alter_yearofexperience_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YearOfExperience',
        ),
    ]
