# Generated by Django 5.2.1 on 2025-06-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("unverifiedsickleave", "0001_initial")]

    operations = [migrations.RenameField(model_name="sickleavebalance", old_name="verified_family_care_balance", new_name="used_FVSL")]
