# Generated by Django 5.2.1 on 2025-08-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "unverifiedsickleave",
            "0003_alter_sickleavebalance_unverified_sick_balance_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sickleavebalance",
            table="sick_leave_balances",
        ),
    ]
