# Generated by Django 5.2.1 on 2025-08-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employeetype", "0002_employeetype_created_at_employeetype_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeetype",
            options={
                "verbose_name": "Employee Type",
                "verbose_name_plural": "Employee Types",
            },
        ),
        migrations.AlterModelTable(
            name="employeetype",
            table="employee_types",
        ),
    ]
