# Generated by Django 5.2.1 on 2025-09-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='The exact UTC date and time when this pay period begins.', verbose_name='Start Date and Time')),
                ('end_date', models.DateTimeField(help_text='The exact UTC date and time when this pay period ends. Typically 23:59:59 on the end day of the period.', verbose_name='End Date and Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this pay period was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this pay period was last updated.', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Pay Period',
                'verbose_name_plural': 'Pay Periods',
                'db_table': 'pay_periods',
                'ordering': ['start_date'],
            },
        ),
    ]
