# Generated by Django 5.2.1 on 2025-06-13 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payperiod", "0001_initial")]

    operations = [migrations.AddField(model_name="payperiod", name="created_at", field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text="The date and time when this pay period was created.", verbose_name="Created At"), preserve_default=False), migrations.AddField(model_name="payperiod", name="updated_at", field=models.DateTimeField(auto_now=True, help_text="The date and time when this pay period was last updated.", verbose_name="Updated At"))]
