# Generated by Django 5.2.1 on 2025-08-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payperiod", "0002_payperiod_created_at_payperiod_updated_at"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="payperiod",
            table="pay_periods",
        ),
    ]
