# Generated by Django 5.2.1 on 2025-08-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holiday", "0002_holiday_created_at_holiday_updated_at"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="holiday",
            table="holidays",
        ),
    ]
