# Generated by Django 5.2.1 on 2025-06-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_time_off",
            field=models.BooleanField(default=False),
        ),
    ]
