# Generated by Django 5.2.1 on 2025-08-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0003_userprofile_is_manager_userprofile_is_time_off"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Department Unit",
                "verbose_name_plural": "Department Units",
            },
        ),
        migrations.AlterModelTable(
            name="department",
            table="department_units",
        ),
    ]
