# Generated by Django 5.2.1 on 2025-08-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0004_alter_department_options_alter_department_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Employee Profile",
                "verbose_name_plural": "Employee Profiles",
            },
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="employee_profiles",
        ),
    ]
