# Generated by Django 5.2.1 on 2025-09-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_userprofile_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tenure',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, null=True),
        ),
    ]
