# Generated by Django 5.2.1 on 2025-05-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("employeetype", "0001_initial"), ("payfrequency", "0003_remove_pay_frequency_user")]

    operations = [
        migrations.CreateModel(
            name="AccrualRates",
            fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("year_of_experience", models.IntegerField(choices=[(1, "1 Year(s)"), (2, "2 Year(s)"), (3, "3 Year(s)"), (4, "4 Year(s)"), (5, "5 Year(s)"), (6, "6 Year(s)"), (7, "7 Year(s)"), (8, "8 Year(s)"), (9, "9 Year(s)"), (10, "10 Year(s)"), (11, "11 Year(s)")])), ("accrual_rate", models.FloatField(default=0.0)), ("annual_accrual_rate", models.FloatField(default=0.0)), ("employee_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="accrual_rates", to="employeetype.employeetype")), ("pay_frequency", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="accrual_rates", to="payfrequency.pay_frequency"))],
            options={"verbose_name": "Accrual Rate", "verbose_name_plural": "Accrual Rates", "unique_together": {("year_of_experience", "employee_type", "pay_frequency")}},
        )
    ]
