# Generated by Django 5.2.1 on 2025-08-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accuralrates", "0003_accrualrates_created_at_accrualrates_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accrualrates",
            options={
                "verbose_name": "PTO Accrual Rate",
                "verbose_name_plural": "PTO Accrual Rates",
            },
        ),
        migrations.AlterModelTable(
            name="accrualrates",
            table="pto_accrual_rates",
        ),
    ]
